### ISSUE TITLE
Missing curl on Windows

### ISSUE THREAD

**Issue by topac** [oneclick/knap-build#1]
Hi, I cloned this repo and the recipes too on windows but when I try to install any recipe:

```
--> Detected platform: i686-w64-mingw32 (x86-windows)
--> About to process libffi version 3.0.10 (x86-windows)
--> Fetching files...
knapsack/utils.rb:16:in `spawn': No such file or directory - curl (Errno::ENOENT)
        from knapsack/utils.rb:16:in `download'
        from knapsack/recipe/helpers/fetcher.rb:22:in `block (2 levels) in define_fetcher'
        from knapsack/recipe/helpers/fetcher.rb:19:in `each'
        from knapsack/recipe/helpers/fetcher.rb:19:in `block in define_fetcher'
        from knapsack/recipe.rb:135:in `instance_exec'
        from knapsack/recipe.rb:135:in `block in perform'
        from knapsack/recipe.rb:252:in `checkpoint'
        from knapsack/recipe.rb:131:in `perform'
        from knapsack/recipe.rb:161:in `block in cook'
        from knapsack/recipe.rb:160:in `each'
        from knapsack/recipe.rb:160:in `cook'
        from bin/knap-build.rb:84:in `<main>'
        from bin/knap-build.rb:in `eval'
```

**Comment by topac** [comment]
And also the tar command! Can I submit a pull request to drop the dependency on tar and curl?

**Comment by Azolo** [comment]
As long as the existing recipes can still be built, I don't see any problems with that.

The project does have a quite a few undocumented dependencies and silent failures.
I just don't remember/know what they are. So yeah, hack away and make the project better.

If you happen to do something that doesn't quite fit the overall purpose of the project then we can talk about it. But my view is: The best solution to the problem is the one that gets built.

**Comment by topac** [comment]
I agree with you. Is there an automated way to test all the builds? Otherwise i'm gonna have to write a script that simply call knap-build on all the available recipes.

**Comment by Azolo** [comment]
There isn't. If you wanted to add something like that to the project itself that would probably be ok.

Or if you see something you might think would be nice but don't want do it yourself, open up an issue and I'll flag it as feature request and try to get to it if I get a chance.

**Comment by topac** [comment]
@Azolo I created this pull request https://github.com/oneclick/knap-build/pull/2
Builds are ok
